In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [22]:
data = [[3, 4], [2, 3], [1, 4], [1, 1]]

In [23]:
scaler = StandardScaler()

In [24]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [25]:
scaler.mean_

array([ 1.75,  3.  ])

In [39]:
scaler.var_

array([ 0.6875,  1.5   ])

In [26]:
scaler.transform(data)

array([[ 1.50755672,  0.81649658],
       [ 0.30151134,  0.        ],
       [-0.90453403,  0.81649658],
       [-0.90453403, -1.63299316]])

## 定義自己的StandardScaler


In [41]:
class mynormalscaler:
    def _init_(self):
        self.data_mean_: None
        self.data_var_:None
            
    def fit(self,data):
        self.data_mean_=np.mean(data,axis=0)
        self.data_var_=np.var(data,axis=0)
        
    def transform(self,data):
        data1=(np.array(data)-self.data_mean_)/np.sqrt(self.data_var_)
        return data1
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)
        

In [43]:
np.mean(data,axis=0)

array([ 1.75,  3.  ])

In [44]:
np.var(data,axis=0)

array([ 0.6875,  1.5   ])

In [45]:
(np.array(data)-scaler.mean_)/np.sqrt(scaler.var_)

array([[ 1.50755672,  0.81649658],
       [ 0.30151134,  0.        ],
       [-0.90453403,  0.81649658],
       [-0.90453403, -1.63299316]])

In [46]:
(np.array(data)-scaler.with_mean)/(scaler.with_std)

array([[ 2.,  3.],
       [ 1.,  2.],
       [ 0.,  3.],
       [ 0.,  0.]])

In [47]:
myscaler=mynormalscaler()

In [48]:
data

[[3, 4], [2, 3], [1, 4], [1, 1]]

In [49]:
myscaler.fit(data)

In [50]:
myscaler.data_mean_

array([ 1.75,  3.  ])

In [51]:
myscaler.data_var_

array([ 0.6875,  1.5   ])

In [52]:
myscaler.transform(data)

array([[ 1.50755672,  0.81649658],
       [ 0.30151134,  0.        ],
       [-0.90453403,  0.81649658],
       [-0.90453403, -1.63299316]])

In [54]:
new=mynormalscaler()

In [55]:
new.fit_transform(data)

array([[ 1.50755672,  0.81649658],
       [ 0.30151134,  0.        ],
       [-0.90453403,  0.81649658],
       [-0.90453403, -1.63299316]])